# Generated by Django 5.2.17 on 2026-09-30 14:26

import desk.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('organisation', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('client', 'Client'), ('operator', 'Operator'), ('admin', 'Admin')], default='client', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', desk.models.DeskUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DatasetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('episodes_requested', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('deadline', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_progress', 'In progress'), ('delivered', 'Delivered'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dataset_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_id', models.CharField(max_length=50, unique=True)),
                ('robot_id', models.CharField(choices=[('arm-01', 'arm-01'), ('arm-02', 'arm-02'), ('arm-03', 'arm-03'), ('mobile-01', 'mobile-01'), ('humanoid-01', 'humanoid-01')], max_length=20)),
                ('task_name', models.CharField(max_length=200)),
                ('recorded_at', models.DateTimeField()),
                ('duration_seconds', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('operator_name', models.CharField(max_length=150)),
                ('quality', models.CharField(choices=[('good', 'Good'), ('usable', 'Usable'), ('bad', 'Bad')], max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['recorded_at', 'robot_id'], name='episode_recorded_robot_idx'), models.Index(fields=['task_name', 'quality'], name='episode_task_quality_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_seconds__gt', 0)), name='episode_positive_duration'), models.CheckConstraint(condition=models.Q(('quality__in', ['good', 'usable', 'bad'])), name='episode_valid_quality'), models.CheckConstraint(condition=models.Q(('robot_id__in', ['arm-01', 'arm-02', 'arm-03', 'mobile-01', 'humanoid-01'])), name='episode_known_robot')],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episode_assignments', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='desk.datasetrequest')),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assignment', to='desk.episode')),
            ],
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('in_progress', 'In progress'), ('delivered', 'Delivered'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20)),
                ('to_status', models.CharField(choices=[('submitted', 'Submitted'), ('in_progress', 'In progress'), ('delivered', 'Delivered'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_status_changes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to='desk.datasetrequest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['client', 'operator', 'admin'])), name='user_valid_role'),
        ),
        migrations.AddConstraint(
            model_name='datasetrequest',
            constraint=models.CheckConstraint(condition=models.Q(('episodes_requested__gte', 1)), name='request_positive_count'),
        ),
        migrations.AddConstraint(
            model_name='datasetrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['submitted', 'in_progress', 'delivered', 'accepted', 'rejected'])), name='request_valid_status'),
        ),
    ]
